name: My-Pipeline
'on':
  workflow_dispatch: null
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          if ! command -v npm > /dev/null 2>&1; then npm install -g npm; fi
          npm install

      - name: Build Project
        run: npm run build
